export const baseUrl = 'https://pixelmirror.me'
export const loginUrl = baseUrl + '/login/'
export const staffUrl = baseUrl + '/api/staffs/'
export const rdUrl = baseUrl + '/api/residentdevelopers/'
export const categoryUrl = baseUrl + '/api/categories/'
export const categoryTypesUrl = baseUrl + '/api/categoryTypes/'
export const categoriesForOptions = baseUrl + '/api/categories/categoriesForOptions/'
export const subcategoriesForOptions = baseUrl + '/api/categories/subcategoriesForOptions/'
export const itemUrl = baseUrl + '/api/items/'
export const staffsForOptions = baseUrl + '/api/staffs/staffsforoptions/'
export const loanUrl = baseUrl + '/api/loans/'
export const loanOptions = baseUrl + '/api/loanoptions/'
export const userOptions = baseUrl + '/api/users/usersforoptions/'
export const visitPurpose = baseUrl + '/api/visitpurposes/'
export const visitPurposesForOptions = baseUrl + '/api/visitPurposes/visitPurposesForOptions/'
export const visitors = baseUrl + '/api/visitors/'
export const logoutUrl = baseUrl + '/logout/'

// Report Generation / Graphs
export const visitorDataUrl = baseUrl + '/api/reports/visitorData/'
export const loanArchiveDataUrl = baseUrl + '/api/reports/loanArchiveData/'
//  For actual production, don't need base url, vue will be part of nodejs program, so '/' will suffice
